import { Layer, RGBColor, LayoutEditConfig } from '@/types';

// Cores do sistema atual
const systemColors = {
  primary: { r: 0, g: 166, b: 225 }, // #00a6e1 sky-600
  secondary: { r: 56, g: 189, b: 248 }, // #38bdf8 sky-400
  background: { r: 2, g: 12, b: 27 }, // #020c1b
  dark: { r: 15, g: 23, b: 42 }, // #0f172a
  slate: { r: 148, g: 163, b: 184 }, // #94a3b8
  white: { r: 255, g: 255, b: 255 },
  green: { r: 16, g: 185, b: 129 }, // #10b981
  red: { r: 239, g: 68, b: 68 }, // #ef4444
};

// Cria um layout padrão baseado no sistema atual
export function createDefaultLayout(): LayoutEditConfig {
  const layers: Layer[] = [
    // Header/Banner
    {
      id: 'hero',
      type: 'shape',
      label: 'Hero Background',
      visible: true,
      x: 0,
      y: 0,
      width: 1200,
      height: 300,
      rotation: 0,
      opacity: 1,
      zIndex: 0,
      backgroundColor: systemColors.dark,
      borderColor: systemColors.primary,
      borderWidth: 0,
      borderRadius: 0,
    },
    // Título Principal
    {
      id: 'title',
      type: 'text',
      label: 'Título Principal',
      visible: true,
      x: 50,
      y: 80,
      width: 1100,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      text: 'Serviços Profissionais da Ederass',
      fontSize: 48,
      fontFamily: 'inter',
      fontColor: systemColors.white,
      fontWeight: 'bold',
      textAlign: 'center',
      backgroundColor: undefined,
      borderColor: undefined,
      borderWidth: 0,
      borderRadius: 0,
    },
    // Descrição
    {
      id: 'description',
      type: 'text',
      label: 'Descrição',
      visible: true,
      x: 50,
      y: 180,
      width: 1100,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      text: 'Regularizações, seguros e documentações com expertise de 20+ anos',
      fontSize: 18,
      fontFamily: 'inter',
      fontColor: systemColors.secondary,
      fontWeight: 'normal',
      textAlign: 'center',
      backgroundColor: undefined,
      borderColor: undefined,
      borderWidth: 0,
      borderRadius: 0,
    },
    // Card de Serviço 1
    {
      id: 'card1',
      type: 'shape',
      label: 'Card Serviço 1',
      visible: true,
      x: 50,
      y: 350,
      width: 350,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      backgroundColor: { r: 30, g: 50, b: 100 },
      borderColor: systemColors.primary,
      borderWidth: 1,
      borderRadius: 12,
    },
    {
      id: 'card1-title',
      type: 'text',
      label: 'Card 1 Título',
      visible: true,
      x: 70,
      y: 370,
      width: 310,
      height: 50,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      text: '📝 Documentação',
      fontSize: 20,
      fontFamily: 'inter',
      fontColor: systemColors.secondary,
      fontWeight: 'bold',
      textAlign: 'left',
      backgroundColor: undefined,
      borderColor: undefined,
      borderWidth: 0,
      borderRadius: 0,
    },
    {
      id: 'card1-desc',
      type: 'text',
      label: 'Card 1 Descrição',
      visible: true,
      x: 70,
      y: 420,
      width: 310,
      height: 110,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      text: 'Regularizações completas para sua embarcação com documentação atualizada',
      fontSize: 13,
      fontFamily: 'inter',
      fontColor: systemColors.slate,
      fontWeight: 'normal',
      textAlign: 'left',
      backgroundColor: undefined,
      borderColor: undefined,
      borderWidth: 0,
      borderRadius: 0,
    },
    // Card de Serviço 2
    {
      id: 'card2',
      type: 'shape',
      label: 'Card Serviço 2',
      visible: true,
      x: 425,
      y: 350,
      width: 350,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      backgroundColor: { r: 30, g: 50, b: 100 },
      borderColor: systemColors.primary,
      borderWidth: 1,
      borderRadius: 12,
    },
    {
      id: 'card2-title',
      type: 'text',
      label: 'Card 2 Título',
      visible: true,
      x: 445,
      y: 370,
      width: 310,
      height: 50,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      text: '🛡️ Seguros',
      fontSize: 20,
      fontFamily: 'inter',
      fontColor: systemColors.secondary,
      fontWeight: 'bold',
      textAlign: 'left',
      backgroundColor: undefined,
      borderColor: undefined,
      borderWidth: 0,
      borderRadius: 0,
    },
    {
      id: 'card2-desc',
      type: 'text',
      label: 'Card 2 Descrição',
      visible: true,
      x: 445,
      y: 420,
      width: 310,
      height: 110,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      text: 'Proteção total para sua embarcação com coberturas personalizadas',
      fontSize: 13,
      fontFamily: 'inter',
      fontColor: systemColors.slate,
      fontWeight: 'normal',
      textAlign: 'left',
      backgroundColor: undefined,
      borderColor: undefined,
      borderWidth: 0,
      borderRadius: 0,
    },
    // Card de Serviço 3
    {
      id: 'card3',
      type: 'shape',
      label: 'Card Serviço 3',
      visible: true,
      x: 800,
      y: 350,
      width: 350,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      backgroundColor: { r: 30, g: 50, b: 100 },
      borderColor: systemColors.primary,
      borderWidth: 1,
      borderRadius: 12,
    },
    {
      id: 'card3-title',
      type: 'text',
      label: 'Card 3 Título',
      visible: true,
      x: 820,
      y: 370,
      width: 310,
      height: 50,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      text: '📜 Licenças',
      fontSize: 20,
      fontFamily: 'inter',
      fontColor: systemColors.secondary,
      fontWeight: 'bold',
      textAlign: 'left',
      backgroundColor: undefined,
      borderColor: undefined,
      borderWidth: 0,
      borderRadius: 0,
    },
    {
      id: 'card3-desc',
      type: 'text',
      label: 'Card 3 Descrição',
      visible: true,
      x: 820,
      y: 420,
      width: 310,
      height: 110,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      text: 'Licenças profissionais e amadorais para navegação segura',
      fontSize: 13,
      fontFamily: 'inter',
      fontColor: systemColors.slate,
      fontWeight: 'normal',
      textAlign: 'left',
      backgroundColor: undefined,
      borderColor: undefined,
      borderWidth: 0,
      borderRadius: 0,
    },
    // Botão CTA
    {
      id: 'cta-button',
      type: 'button',
      label: 'Botão CTA',
      visible: true,
      x: 500,
      y: 620,
      width: 200,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 4,
      text: 'Explorar Serviços',
      fontSize: 16,
      fontFamily: 'inter',
      fontColor: systemColors.white,
      fontWeight: 'bold',
      textAlign: 'center',
      backgroundColor: systemColors.primary,
      borderColor: systemColors.primary,
      borderWidth: 0,
      borderRadius: 8,
    },
  ];

  return {
    id: 'default-layout',
    name: 'Layout Padrão - Ederass',
    description: 'Layout padrão do sistema com estilo sky-blue',
    canvasWidth: 1200,
    canvasHeight: 720,
    backgroundColor: systemColors.background,
    layers,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  };
}

// Exportar cores do sistema para uso em outras partes
export { systemColors };
